import './globals.css'
import Header from "./components/Header";
import { Mulish } from 'next/font/google';
import Footer from "./components/Footer";

const mulish = Mulish({
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
    display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function MyApp({ Component, pageProps }) {
    return (
        <>
         
            <Header />
            <Component {...pageProps} />
            <Footer />
        </>
    );
}
export default MyApp;